spring:
  datasource:
    url: jdbc:h2:mem:test_db
    username: sa
    password: password
  jpa:
    open-in-view: false
    show-sql: true

aws:
  region: us-east-1
  access-key: access-key-test
  secret-key: secret-key-test
  bucket-name: bucket-name-test