spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cloud_file_manager
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    show-sql: true
